1 check_qsat: (TC18) Type mismatch in comparison: REAL,wp [*](*) compared to REAL,wp 
2 check_qsat: (TC19) Equality test on reals is not reliable
3 check_qsat: (TC01) Expression is expected to be numeric, and is here REAL,wp [*](*)
4 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy1
5 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy2
6 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy1
7 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy1
8 check_qsat: (TC18) Type mismatch in comparison: REAL,wp [*](*) compared to REAL,wp 
9 check_qsat: (TC19) Equality test on reals is not reliable
10 check_qsat: (TC01) Expression is expected to be numeric, and is here REAL,wp [*](*)
11 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy1
12 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy2
13 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy1
14 check_qsat: (AD12) User help requested: unknown dimension 1 of array pwy1
