!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.13 (r6666) - 27 Nov 2017 17:09
!
!> Fortran module handling geometry for the FV3 model
MODULE FV3JEDI_GEOM_MOD_DIFF
  USE MPP_DOMAINS_MOD_DIFF, ONLY : domain2d, kind_real
  IMPLICIT NONE
  PRIVATE 
  PUBLIC fv3jedi_geom
! data domain
! compute domain
! ------------------------------------------------------------------------------
!> Skinny version of fv_grid_bounds_type
  TYPE FV_GRID_BOUNDS_TYPE
      INTEGER :: isd, ied, jsd, jed
      INTEGER :: isc, iec, jsc, jec
  END TYPE FV_GRID_BOUNDS_TYPE
!From user, maybe via input.nml
!x-dir grid edge points per tile
!y-dir grid edge points per tile
!z-dir grid points global
!Are fields on this geometry hydrostatic
!Processor layout for computation
!Processor layout for read/write
!Number of halo points, normally 3
!FV3 nml file associated with this geom
!FV3 field_table associated with this geom
!A-grid or D-grid in the state vector
!Hardwired or determined
!Is this the root process 
!Size of cubed sphere grid (cell center)
!Number of tracers
!MPP domain
!FV grid bounds
!Tile ID
!Number of tiles, always 6
!Stackmax
!Longitude at cell center
!Latitude at cell center
!Longitude at cell center
!Latitude at cell center
!Grid area
!Model level coefficients
!Pressure at top of domain
!> Fortran derived type to hold geometry data for the FV3JEDI model
  TYPE FV3JEDI_GEOM
      INTEGER :: npx
      INTEGER :: npy
      INTEGER :: npz
      LOGICAL :: hydrostatic
      INTEGER :: layout(2)
      INTEGER :: io_layout(2)
      INTEGER :: halo
      CHARACTER(len=255) :: nml_file
      CHARACTER(len=255) :: trc_file
      CHARACTER(len=255) :: wind_type
      LOGICAL :: am_i_root_pe=.false.
      INTEGER :: size_cubic_grid
      INTEGER :: ntracers
      TYPE(DOMAIN2D) :: domain
      TYPE(FV_GRID_BOUNDS_TYPE) :: bd
      INTEGER :: ntile
      INTEGER :: ntiles=6
      INTEGER :: stackmax
      REAL(kind=kind_real), ALLOCATABLE :: grid_lon(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: grid_lat(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: egrid_lon(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: egrid_lat(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: area(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: ak(:), bk(:)
      REAL(kind=kind_real) :: ptop
      REAL(kind=kind_real), ALLOCATABLE :: sin_sg(:, :, :)
      REAL(kind=kind_real), ALLOCATABLE :: cos_sg(:, :, :)
      REAL(kind=kind_real), ALLOCATABLE :: cosa_u(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: cosa_v(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: cosa_s(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: rsin_u(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: rsin_v(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: rsin2(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: dxa(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: dya(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: dx(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: dy(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: dxc(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: dyc(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: rarea(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: rarea_c(:, :)
      REAL(kind=kind_real), ALLOCATABLE :: edge_w(:)
      REAL(kind=kind_real), ALLOCATABLE :: edge_e(:)
      REAL(kind=kind_real), ALLOCATABLE :: edge_s(:)
      REAL(kind=kind_real), ALLOCATABLE :: edge_n(:)
      REAL(kind=kind_real), ALLOCATABLE :: grid(:, :, :)
      REAL(kind=kind_real), ALLOCATABLE :: agrid(:, :, :)
      LOGICAL :: sw_corner, se_corner, ne_corner, nw_corner
  END TYPE FV3JEDI_GEOM
END MODULE FV3JEDI_GEOM_MOD_DIFF
