1 (TC42) Recursivity: esinit-->qsatice0-->esinit
2 (TC42) Recursivity: qsatlqu0-->esinit-->qsatlqu0
3 qsat0: (TC19) Equality test on reals is not reliable
4 qsat0: (TC19) Equality test on reals is not reliable
5 qsat0: (TC19) Equality test on reals is not reliable
6 dqsat0: (TC19) Equality test on reals is not reliable
7 dqsat0: (TC19) Equality test on reals is not reliable
8 dqsat0: (TC19) Equality test on reals is not reliable
9 rase: Command: Input variable(s) clw, cnv_prc3, vho, cnv_updfrc, uho, flxd have their derivative modified in rase: added to independents
10 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estfrz
11 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)first
12 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estlqu
13 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estble[1:tablesize]
14 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)utbl
15 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblw[1:tablesize]
16 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblx[1:tablesize]
17 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estfrz
18 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)first
19 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estlqu
20 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estble[1:tablesize]
21 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)utbl
22 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblw[1:tablesize]
23 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblx[1:tablesize]
24 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estfrz
25 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)first
26 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estlqu
27 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estble[1:tablesize]
28 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)utbl
29 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblw[1:tablesize]
30 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblx[1:tablesize]
31 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estfrz
32 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)first
33 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estlqu
34 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estble[1:tablesize]
35 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)utbl
36 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblw[1:tablesize]
37 rase: (AD14) Checkpointing this call to strap needs to save an undeclared side-effect variable: (global)estblx[1:tablesize]
38 rase: (AD14) Summary: differentiated procedure of rase needs to save undeclared side-effect variables estblx, estblw, utbl, estble, estlqu, first, estfrz, from MODULE geos_utilsmod
39 cloude: (TC56) Declaration of mask uses hidden variable (ic)
40 cloude: (TC56) Declaration of mask uses hidden variable (k)
41 finddtls: (TC30) Type mismatch in argument 1 of procedure random_seed, expected INTEGER, is here INTEGER(*)
42 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)estblx[1:tablesize]
43 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)estblw[1:tablesize]
44 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)utbl
45 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)estble[1:tablesize]
46 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)estlqu
47 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)first
48 strap: (AD14) Checkpointing this call to dqsat0 needs to save an undeclared side-effect variable: (global)estfrz
49 strap: (AD14) Summary: differentiated procedure of strap needs to save undeclared side-effect variables estfrz, first, estlqu, estble, utbl, estblw, estblx, from MODULE geos_utilsmod
50 erfapp: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
51 erfapp: (TC16) Type mismatch in assignment: REAL*8 receives DOUBLE PRECISION
