!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.13 (r6666) - 27 Nov 2017 17:09
!
!***********************************************************************
!*                   GNU General Public License                        *
!* This file is a part of fvGFS.                                       *
!*                                                                     *
!* fvGFS is free software; you can redistribute it and/or modify it    *
!* and are expected to follow the terms of the GNU General Public      *
!* License as published by the Free Software Foundation; either        *
!* version 2 of the License, or (at your option) any later version.    *
!*                                                                     *
!* fvGFS is distributed in the hope that it will be useful, but        *
!* WITHOUT ANY WARRANTY; without even the implied warranty of          *
!* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU   *
!* General Public License for more details.                            *
!*                                                                     *
!* For the full text of the GNU General Public License,                *
!* write to: Free Software Foundation, Inc.,                           *
!*           675 Mass Ave, Cambridge, MA 02139, USA.                   *
!* or see:   http://www.gnu.org/licenses/gpl.html                      *
!***********************************************************************
MODULE FV_FILL_MOD_DIFF
  USE MPP_DOMAINS_MOD_DIFF, ONLY : mpp_update_domains, &
& mpp_update_domains_adm, domain2d
  IMPLICIT NONE
  PUBLIC fillz
  PUBLIC fill2d

CONTAINS
  SUBROUTINE FILLZ(im, km, nq, q, dp)
    IMPLICIT NONE
!Stubbed, highly nonlinear process
! No. of longitudes
    INTEGER, INTENT(IN) :: im
! No. of levels
    INTEGER, INTENT(IN) :: km
! Total number of tracers
    INTEGER, INTENT(IN) :: nq
! pressure thickness
    REAL, INTENT(IN) :: dp(im, km)
! tracer mixing ratio
    REAL, INTENT(INOUT) :: q(im, km, nq)
! !LOCAL VARIABLES:
    LOGICAL :: zfix(im)
    REAL :: dm(km)
    INTEGER :: i, k, ic, k1
    REAL :: qup, qly, dup, dq, sum0, sum1, fac
  END SUBROUTINE FILLZ
  SUBROUTINE FILL2D(is, ie, js, je, ng, km, q, delp, area, domain, &
&   nested, npx, npy)
    IMPLICIT NONE
!Stubbed, highly nonlinear process
! This is a diffusive type filling algorithm
    TYPE(DOMAIN2D), INTENT(INOUT) :: domain
    INTEGER, INTENT(IN) :: is, ie, js, je, ng, km, npx, npy
    LOGICAL, INTENT(IN) :: nested
    REAL, INTENT(IN) :: area(is-ng:ie+ng, js-ng:je+ng)
    REAL, INTENT(IN) :: delp(is-ng:ie+ng, js-ng:je+ng, km)
    REAL, INTENT(INOUT) :: q(is-ng:ie+ng, js-ng:je+ng, km)
! LOCAL VARIABLES:
    REAL, DIMENSION(is-ng:ie+ng, js-ng:je+ng, km) :: qt
    REAL, DIMENSION(is:ie+1, js:je) :: fx
    REAL, DIMENSION(is:ie, js:je+1) :: fy
    REAL, PARAMETER :: dif=0.25
    INTEGER :: i, j, k
    INTEGER :: is1, ie1, js1, je1
  END SUBROUTINE FILL2D
END MODULE FV_FILL_MOD_DIFF
