!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.9 (r5096) - 24 Feb 2014 16:53
!
!  Differentiation of fill_friendly in forward (tangent) mode:
!   variations   of useful results: q
!   with respect to varying inputs: q
!   RW status of diff variables: q:in-out
SUBROUTINE FILL_FRIENDLY_D(im, jm, lm, q, qd, dp)
  IMPLICIT NONE
!Inputs
  INTEGER, INTENT(IN) :: im, jm, lm
  REAL*8, INTENT(IN) :: dp(im, jm, lm)
!Prognostic
  REAL*8, INTENT(INOUT) :: q(im, jm, lm)
  REAL*8, INTENT(INOUT) :: qd(im, jm, lm)
!Locals
  INTEGER :: i, j, l
  REAL*8 :: qtemp1(im, jm), qtemp2(im, jm)
  REAL*8 :: qtemp1d(im, jm), qtemp2d(im, jm)
  INTRINSIC ABS
  INTRINSIC MAX
  REAL*8 :: abs0
  qtemp1 = 0.0
  qtemp1d = 0.0_8
  DO l=1,lm
    qtemp1d(:, :) = qtemp1d(:, :) + dp(:, :, l)*qd(:, :, l)
    qtemp1(:, :) = qtemp1(:, :) + q(:, :, l)*dp(:, :, l)
  END DO
  DO i=1,im
    DO j=1,jm
      DO l=1,lm
        IF (q(i, j, l) .LT. 0.0) THEN
          qd(i, j, l) = 0.0_8
          q(i, j, l) = 0.0
        END IF
      END DO
    END DO
  END DO
  qtemp2 = 0.0
  qtemp2d = 0.0_8
  DO l=1,lm
    qtemp2d(:, :) = qtemp2d(:, :) + dp(:, :, l)*qd(:, :, l)
    qtemp2(:, :) = qtemp2(:, :) + q(:, :, l)*dp(:, :, l)
  END DO
  DO i=1,im
    DO j=1,jm
      IF (qtemp2(i, j) .GE. 0.) THEN
        abs0 = qtemp2(i, j)
      ELSE
        abs0 = -qtemp2(i, j)
      END IF
      IF (abs0 .GT. 0.0) THEN
        IF (qtemp1(i, j)/qtemp2(i, j) .LT. 0.0) THEN
          qtemp2d(i, j) = 0.0_8
          qtemp2(i, j) = 0.0
        ELSE
          qtemp2d(i, j) = (qtemp1d(i, j)*qtemp2(i, j)-qtemp1(i, j)*&
&           qtemp2d(i, j))/qtemp2(i, j)**2
          qtemp2(i, j) = qtemp1(i, j)/qtemp2(i, j)
        END IF
      END IF
    END DO
  END DO
  DO l=1,lm
    qd(:, :, l) = qd(:, :, l)*qtemp2(:, :) + q(:, :, l)*qtemp2d(:, :)
    q(:, :, l) = q(:, :, l)*qtemp2(:, :)
  END DO
END SUBROUTINE FILL_FRIENDLY_D

