MODULE CLOUD

IMPLICIT NONE

PRIVATE

!Make subroutines public for adjoint checkpointing
PUBLIC CLOUD_DRIVER, CLOUD_TIDY, MELTFREEZE, GET_ICE_FRACTION, CONVEC_SRC, PDF_WIDTH, LS_CLOUD, &
       AUTOCONVERSION_LS, AUTOCONVERSION_CNV, ICE_SETTLEFALL_LS, ICE_SETTLEFALL_CNV, PRECIPANDEVAP, &
       PDFFRAC, PDFCONDENSATE, CONS_SUNDQ3, CONS_ALHX, CONS_MICROPHYS, MARSHPALM, EVAP_CNV, SUBL_CNV, LDRADIUS, &
       DQSAT_BAC, DQSATs_BAC

CONTAINS

