1 a2b_ord4: (TC01) Expression is expected to be numeric, and is here INTEGER POINTER
2 a2b_ord4: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
3 a2b_ord4: (TC16) Type mismatch in assignment: REAL receives REAL*8
4 a2b_ord4: (TC16) Type mismatch in assignment: REAL receives REAL*8
5 a2b_ord4: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
6 a2b_ord4: (TC16) Type mismatch in assignment: REAL receives REAL*8
7 a2b_ord4: (TC16) Type mismatch in assignment: REAL receives REAL*8
8 a2b_ord4: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
9 a2b_ord4_fb: (TC01) Expression is expected to be numeric, and is here INTEGER POINTER
10 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
11 a2b_ord4_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
12 a2b_ord4_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
13 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
14 a2b_ord4_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
15 a2b_ord4_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
16 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
17 a2b_ord2: (TC01) Expression is expected to be numeric, and is here INTEGER POINTER
18 a2b_ord2: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
19 a2b_ord2: (TC16) Type mismatch in assignment: REAL receives REAL*8
20 a2b_ord2: (TC16) Type mismatch in assignment: REAL receives REAL*8
21 a2b_ord2: (TC16) Type mismatch in assignment: REAL receives REAL*8
22 a2b_ord2: (TC16) Type mismatch in assignment: REAL receives REAL*8
23 great_circle_dist: (TC16) Type mismatch in assignment: REAL receives REAL*8
24 g_sum: (TC16) Type mismatch in assignment: REAL receives REAL*8
25 g_sum: (TC16) Type mismatch in assignment: REAL receives REAL*8
26 g_sum: (TC16) Type mismatch in assignment: REAL receives REAL*8
27 tracer_2d_nested: (TC15) Argument of logical operator is expected to be boolean, and is here LOGICAL POINTER
28 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
29 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
30 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
31 d_sw: (TC16) Type mismatch in assignment: REAL receives REAL*8
32 d_sw: (TC16) Type mismatch in assignment: REAL receives REAL*8
33 d_sw: (TC16) Type mismatch in assignment: REAL receives REAL*8
34 compute_divergence_damping: (TC16) Type mismatch in assignment: REAL receives REAL*8
35 compute_divergence_damping: (TC16) Type mismatch in assignment: REAL receives REAL*8
36 compute_divergence_damping: (TC16) Type mismatch in assignment: REAL receives REAL*8
37 compute_divergence_damping: (TC16) Type mismatch in assignment: REAL receives REAL*8
38 compute_divergence_damping: (TC16) Type mismatch in assignment: REAL receives REAL*8
39 compute_divergence_damping: (TC16) Type mismatch in assignment: REAL receives REAL*8
40 compute_divergence_damping_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
41 compute_divergence_damping_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
42 compute_divergence_damping_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
43 compute_divergence_damping_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
44 compute_divergence_damping_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
45 compute_divergence_damping_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
46 fv_tp_2d: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
47 fv_tp_2d: (TC16) Type mismatch in assignment: REAL receives REAL*8
48 fv_tp_2d: (TC16) Type mismatch in assignment: REAL receives REAL*8
49 fv_tp_2d_fb: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
50 fv_tp_2d_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
51 fv_tp_2d_fb: (TC16) Type mismatch in assignment: REAL receives REAL*8
52 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
53 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
54 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
55 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
56 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
57 dyn_core: (TC15) Argument of logical operator is expected to be boolean, and is here LOGICAL POINTER
58 dyn_core: (TC16) Type mismatch in assignment: REAL receives REAL*8
59 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
60 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
61 dyn_core: (TC01) Expression is expected to be numeric, and is here INTEGER POINTER
62 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
63 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
64 dyn_core: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
65 adv_pe: (TC16) Type mismatch in assignment: REAL receives REAL*8
66 adv_pe: (TC16) Type mismatch in assignment: REAL receives REAL*8
67 adv_pe: (TC16) Type mismatch in assignment: REAL receives REAL*8
68 geopk: (TC16) Type mismatch in assignment: REAL receives REAL*8
69 geopk: (TC16) Type mismatch in assignment: REAL receives REAL*8
70 geopk: (TC16) Type mismatch in assignment: REAL receives REAL*8
71 del2_cubed: (TC16) Type mismatch in assignment: REAL receives REAL*8
72 rayleigh_fast: (TC16) Type mismatch in assignment: REAL receives REAL*8
73 lagrangian_to_eulerian: (TC16) Type mismatch in assignment: REAL receives REAL*8
74 lagrangian_to_eulerian: (TC16) Type mismatch in assignment: REAL receives REAL*8
75 lagrangian_to_eulerian: (TC16) Type mismatch in assignment: REAL receives REAL*8
76 steepz: (TC19) Equality test on reals is not reliable
77 ppm_limiters: (TC19) Equality test on reals is not reliable
78 fv_dynamics: (TC15) Argument of logical operator is expected to be boolean, and is here LOGICAL POINTER
79 fv_dynamics: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
80 fv_dynamics: (TC01) Expression is expected to be numeric, and is here INTEGER POINTER
81 fv_dynamics: (TC16) Type mismatch in assignment: REAL receives REAL*8
82 fv_dynamics: (TC02) Expression is expected to be boolean, and is here LOGICAL POINTER
83 fv_dynamics: (TC16) Type mismatch in assignment: REAL receives REAL*8
84 fv_dynamics: (DF02) Potential aliasing in calling function setup_nested_grid_bcs, between arguments 18 21
85 fv_dynamics: (DF03) variable t2 is used before initialized
86 fv_dynamics: (DF03) variable t1 is used before initialized
87 rayleigh_super: (TC16) Type mismatch in assignment: REAL receives REAL*8
88 rayleigh_friction: (TC16) Type mismatch in assignment: REAL receives REAL*8
89 setup_nested_grid_bcs: Tool: (Collect used pointer ranks) Unexpected operator: none
90 fv_grid_utils_mod_diff: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
91 fv_grid_utils_mod_diff: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
92 fv_grid_utils_mod_diff: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
