!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:30
!
MODULE FV_GRID_TOOLS_MOD_B
  USE FV_MP_MOD_B, ONLY : is, js, ie, je, isd, jsd, ied, jed
  USE FV_ARRAYS_MOD, ONLY : fvprc
  IMPLICIT NONE
  PUBLIC 
  INTEGER :: grid_type
  REAL(fvprc), DIMENSION(:, :), ALLOCATABLE :: area, rarea, dxa, dya, dx&
& , dy, rdxc, rdyc
END MODULE FV_GRID_TOOLS_MOD_B
