!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.13 (r6666) - 27 Nov 2017 17:09
!
MODULE MPP_DOMAINS_MOD_DIFF
  IMPLICIT NONE
  PRIVATE 
  PUBLIC mpp_update_domains, domain2d, kind_real
  PUBLIC mpp_update_domains_tlm
  INTEGER, PARAMETER :: kind_real=8
  TYPE DOMAIN2D
      INTEGER :: dummy
  END TYPE DOMAIN2D
  INTERFACE MPP_UPDATE_DOMAINS
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_2D
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_2D_R8
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_3D
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_3D_R8
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_4D
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_5D
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_2DV
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_3DV
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_4DV
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_5DV
  END INTERFACE

  INTERFACE MPP_UPDATE_DOMAINS_TLM
      MODULE PROCEDURE MPP_UPDATE_DOMAIN2D_3D_R8_TLM
  END INTERFACE


CONTAINS
! mpp_update_domains
! ------------------
  SUBROUTINE MPP_UPDATE_DOMAIN2D_2D(field1, domain, gridtype, complete, &
&   whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_2D
  SUBROUTINE MPP_UPDATE_DOMAIN2D_2D_R8(field1, domain, gridtype, &
&   complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL(kind=8), INTENT(INOUT) :: field1(:, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_2D_R8
  SUBROUTINE MPP_UPDATE_DOMAIN2D_3D(field1, domain, gridtype, complete, &
&   whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_3D
!  Differentiation of mpp_update_domain2d_3d_r8 in forward (tangent) mode:
!   variations   of useful results: field1
!   with respect to varying inputs: field1
  SUBROUTINE MPP_UPDATE_DOMAIN2D_3D_R8_TLM(field1, field1_tl, domain, &
&   gridtype, complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL(kind=8), INTENT(INOUT) :: field1(:, :, :)
    REAL(kind=8), INTENT(INOUT) :: field1_tl(:, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1_tl = 2*field1_tl
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_3D_R8_TLM
  SUBROUTINE MPP_UPDATE_DOMAIN2D_3D_R8(field1, domain, gridtype, &
&   complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL(kind=8), INTENT(INOUT) :: field1(:, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_3D_R8
  SUBROUTINE MPP_UPDATE_DOMAIN2D_4D(field1, domain, gridtype, complete, &
&   whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_4D
  SUBROUTINE MPP_UPDATE_DOMAIN2D_5D(field1, domain, gridtype, complete, &
&   whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :, :, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_5D
  SUBROUTINE MPP_UPDATE_DOMAIN2D_2DV(field1, field2, domain, gridtype, &
&   complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :), field2(:, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
    field2 = 2*field2
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_2DV
  SUBROUTINE MPP_UPDATE_DOMAIN2D_3DV(field1, field2, domain, gridtype, &
&   complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :, :), field2(:, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
    field2 = 2*field2
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_3DV
  SUBROUTINE MPP_UPDATE_DOMAIN2D_4DV(field1, field2, domain, gridtype, &
&   complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :, :, :), field2(:, :, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
    field2 = 2*field2
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_4DV
  SUBROUTINE MPP_UPDATE_DOMAIN2D_5DV(field1, field2, domain, gridtype, &
&   complete, whalo, ehalo, shalo, nhalo)
    IMPLICIT NONE
    REAL, INTENT(INOUT) :: field1(:, :, :, :, :), field2(:, :, :, :, :)
    TYPE(DOMAIN2D), INTENT(IN) :: domain
    INTEGER, OPTIONAL, INTENT(IN) :: gridtype
    LOGICAL, OPTIONAL, INTENT(IN) :: complete
    INTEGER, OPTIONAL, INTENT(IN) :: whalo, ehalo, shalo, nhalo
    field1 = 2*field1
    field2 = 2*field2
  END SUBROUTINE MPP_UPDATE_DOMAIN2D_5DV
END MODULE MPP_DOMAINS_MOD_DIFF
