1 a2b_ord4: (TC01) Expression is expected to be numeric, and is here INTEGER*()
2 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
3 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
4 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
5 a2b_ord2: (TC01) Expression is expected to be numeric, and is here INTEGER*()
6 a2b_ord2: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
7 tracer_2d_nested: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
8 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
9 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
10 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
11 c_sw: (DF03) variable ke[i-1,j] is used before initialized
12 c_sw: (DF03) variable ke[i,j] is used before initialized
13 c_sw: (DF03) variable ke[i,j-1] is used before initialized
14 c_sw: (DF03) variable ke[i,j] is used before initialized
15 fv_tp_2d: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
16 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
17 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
18 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
19 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
20 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
21 dyn_core: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
22 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
23 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
24 dyn_core: (TC01) Expression is expected to be numeric, and is here INTEGER*()
25 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
26 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
27 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
28 steepz: (TC19) Equality test on reals is not reliable
29 ppm_limiters: (TC19) Equality test on reals is not reliable
30 fv_dynamics: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
31 fv_dynamics: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
32 fv_dynamics: (TC01) Expression is expected to be numeric, and is here INTEGER*()
33 fv_dynamics: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
