!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.11 (r5903) - 14 Dec 2015 10:32
!
MODULE GEOS_MOISTGRIDCOMP_D
  USE QSAT_UTIL_D
  USE RAS_D
  USE CLOUDNEW_D
  USE RASPARAMS
  USE CLDPARAMS
  USE MAPL_CONSTANTSMOD
  IMPLICIT NONE
!      call RASE_FAST( IDIM                 , &
!                 IRUN                 , &                 
!                 LM                   , &
!                 ICMIN                , &
!                 DT_MOIST             , &
!                 MAPL8_CP              , &
!                 MAPL8_ALHL            , &
!                 MAPL8_ALHS            , &
!                 MAPL8_TICE            , &
!                 MAPL8_GRAV            , &
!                 SEEDRAS              , &
!                 SIGE                 , &
!                 KCBL                 , &
!                 WGT0                 , &
!                 WGT1                 , &
!                 TPERT                , &
!                 QPERT                , &
!                 TH1                  , &
!                 Q1                   , & 
!                 QSS                  , & 
!                 DQS                  , &
!                 CNV_FRACTION         , &
!                 RASAL2_2d            , &
!                 CO_AUTO              , &
!                 CNV_PLE              , &
!                 PKE                  , &
!                 RASPARAMS              )
  INCLUDE 'preamble'
  PRIVATE 
  PUBLIC moist_run
  PUBLIC moist_run_tlm

CONTAINS
!  Differentiation of moist_run in forward (tangent) mode (with options r8):
!   variations   of useful results: v1 qlls th1 qlcn qils q1 clls
!                qicn clcn u1
!   with respect to varying inputs: v1 qlls th1 qlcn qils q1 clls
!                qicn clcn u1
!   RW status of diff variables: v1:in-out qlls:in-out th1:in-out
!                qlcn:in-out qils:in-out q1:in-out clls:in-out
!                qicn:in-out clcn:in-out u1:in-out
  SUBROUTINE MOIST_RUN_TLM(im, jm, lm, dt_moist, idim, irun, icmin, &
&   doconvec, cnv_ple, pke, plo, pk, sige, iras, jras, wgt0, wgt1, &
&   co_auto, rasparams, cldparams, sclmfdfr, frland, kcbl, ts, kh, &
&   seedras, rasal2_2d, cnv_fraction, itrcr, irccode, cbl_tpert, &
&   cbl_qpert, cbl_tpert_mxocn, cbl_tpert_mxlnd, th1, th1_tl, q1, q1_tl&
&   , u1, u1_tl, v1, v1_tl, ple, qlls, qlls_tl, qlcn, qlcn_tl, qils, &
&   qils_tl, qicn, qicn_tl, clcn, clcn_tl, clls, clls_tl)
    IMPLICIT NONE
!Inputs - not linearized
    INTEGER, INTENT(IN) :: im, jm, lm, idim, irun, icmin, itrcr
    REAL*8, INTENT(IN) :: dt_moist, sige(0:lm)
    INTEGER, DIMENSION(im, jm), INTENT(IN) :: iras, jras
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: wgt0, wgt1
    INTEGER, DIMENSION(im, jm), INTENT(IN) :: kcbl, seedras, doconvec
    REAL*8, DIMENSION(im, jm), INTENT(IN) :: ts, co_auto, frland
    REAL*8, DIMENSION(im, jm, 0:lm), INTENT(IN) :: ple, kh
    TYPE(RASPARAM_TYPE), INTENT(IN) :: rasparams
    TYPE(CLDPARAM_TYPE), INTENT(IN) :: cldparams
    REAL*8, INTENT(IN) :: sclmfdfr, cbl_tpert, cbl_qpert, &
&   cbl_tpert_mxocn, cbl_tpert_mxlnd
    REAL*8, DIMENSION(im, jm, 0:lm), INTENT(IN) :: cnv_ple, pke
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: plo, pk
!Inputs - could linearze but not be sensible, e.g. because stochasitc
    REAL*8, DIMENSION(im, jm), INTENT(IN) :: rasal2_2d, cnv_fraction
!Inouts
    REAL*8, DIMENSION(im, jm, lm), INTENT(INOUT) :: th1, q1, u1, v1
    REAL*8, DIMENSION(im, jm, lm), INTENT(INOUT) :: th1_tl, q1_tl, u1_tl&
&   , v1_tl
    REAL*8, DIMENSION(im, jm, lm), INTENT(INOUT) :: qlls, qlcn, qils, &
&   qicn, clcn, clls
    REAL*8, DIMENSION(im, jm, lm), INTENT(INOUT) :: qlls_tl, qlcn_tl, &
&   qils_tl, qicn_tl, clcn_tl, clls_tl
!Outs
    INTEGER, INTENT(OUT) :: irccode
    REAL*8, DIMENSION(im, jm, lm) :: dqs, qss
    REAL*8, DIMENSION(im, jm, lm) :: dqs_tl, qss_tl
    REAL*8, DIMENSION(im, jm, lm) :: qst3
    REAL*8, DIMENSION(im, jm, lm) :: qst3_tl
    REAL*8, DIMENSION(im, jm, lm) :: dzet, qddf3
    REAL*8, DIMENSION(im, jm, lm) :: dzet_tl, qddf3_tl
    REAL*8, DIMENSION(im, jm) :: tpert, qpert
    REAL*8, DIMENSION(im, jm) :: tpert_tl
    REAL*8, DIMENSION(im, jm) :: mxdiamx
    REAL*8, DIMENSION(im, jm, lm) :: cnv_dqldt, cnv_mfd, cnv_prc3, &
&   cnv_updf, cnv_cvw, entlam
    REAL*8, DIMENSION(im, jm, lm) :: cnv_dqldt_tl, cnv_mfd_tl, &
&   cnv_prc3_tl, cnv_updf_tl
    INTEGER :: i, j, l, k
    CALL PRE_RASE_TLM(im, jm, lm, th1, th1_tl, q1, q1_tl, ts, &
&               cnv_fraction, frland, plo, pke, pk, cbl_tpert, cbl_qpert&
&               , cbl_tpert_mxocn, cbl_tpert_mxlnd, tpert, tpert_tl, &
&               qpert, dqs, dqs_tl, qss, qss_tl)
    CALL RASE_TLM(idim, irun, lm, icmin, dt_moist, doconvec, mapl8_cp, &
&           mapl8_alhl, mapl8_alhs, mapl8_tice, mapl8_grav, seedras, &
&           sige, kcbl, wgt0, wgt1, tpert, tpert_tl, qpert, th1, th1_tl&
&           , q1, q1_tl, u1, u1_tl, v1, v1_tl, qss, qss_tl, dqs, dqs_tl&
&           , cnv_fraction, rasal2_2d, co_auto, cnv_ple, pke, cnv_dqldt&
&           , cnv_dqldt_tl, cnv_mfd, cnv_mfd_tl, cnv_prc3, cnv_prc3_tl, &
&           cnv_updf, cnv_updf_tl, rasparams, itrcr)
    CALL PRE_PROGNO_CLOUD_TLM(im, jm, lm, th1, th1_tl, pk, plo, pke, &
&                       cnv_ple, qst3, qst3_tl, dzet, dzet_tl, qddf3, &
&                       qddf3_tl, cnv_fraction, cldparams)
    CALL PROGNO_CLOUD_TLM(idim, lm, dt_moist, plo, cnv_ple, pk, frland, &
&                   kh, cnv_mfd, cnv_mfd_tl, cnv_dqldt, cnv_dqldt_tl, &
&                   cnv_prc3, cnv_prc3_tl, cnv_updf, cnv_updf_tl, u1, &
&                   u1_tl, v1, v1_tl, th1, th1_tl, q1, q1_tl, qlls, &
&                   qlls_tl, qlcn, qlcn_tl, qils, qils_tl, qicn, qicn_tl&
&                   , clcn, clcn_tl, clls, clls_tl, cldparams, sclmfdfr&
&                   , qst3, qst3_tl, dzet, dzet_tl, qddf3, qddf3_tl, &
&                   cnv_fraction)
  END SUBROUTINE MOIST_RUN_TLM
  SUBROUTINE MOIST_RUN(im, jm, lm, dt_moist, idim, irun, icmin, doconvec&
&   , cnv_ple, pke, plo, pk, sige, iras, jras, wgt0, wgt1, co_auto, &
&   rasparams, cldparams, sclmfdfr, frland, kcbl, ts, kh, seedras, &
&   rasal2_2d, cnv_fraction, itrcr, irccode, cbl_tpert, cbl_qpert, &
&   cbl_tpert_mxocn, cbl_tpert_mxlnd, th1, q1, u1, v1, ple, qlls, qlcn, &
&   qils, qicn, clcn, clls)
    IMPLICIT NONE
!Inputs - not linearized
    INTEGER, INTENT(IN) :: im, jm, lm, idim, irun, icmin, itrcr
    REAL*8, INTENT(IN) :: dt_moist, sige(0:lm)
    INTEGER, DIMENSION(im, jm), INTENT(IN) :: iras, jras
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: wgt0, wgt1
    INTEGER, DIMENSION(im, jm), INTENT(IN) :: kcbl, seedras, doconvec
    REAL*8, DIMENSION(im, jm), INTENT(IN) :: ts, co_auto, frland
    REAL*8, DIMENSION(im, jm, 0:lm), INTENT(IN) :: ple, kh
    TYPE(RASPARAM_TYPE), INTENT(IN) :: rasparams
    TYPE(CLDPARAM_TYPE), INTENT(IN) :: cldparams
    REAL*8, INTENT(IN) :: sclmfdfr, cbl_tpert, cbl_qpert, &
&   cbl_tpert_mxocn, cbl_tpert_mxlnd
    REAL*8, DIMENSION(im, jm, 0:lm), INTENT(IN) :: cnv_ple, pke
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: plo, pk
!Inputs - could linearze but not be sensible, e.g. because stochasitc
    REAL*8, DIMENSION(im, jm), INTENT(IN) :: rasal2_2d, cnv_fraction
!Inouts
    REAL*8, DIMENSION(im, jm, lm), INTENT(INOUT) :: th1, q1, u1, v1
    REAL*8, DIMENSION(im, jm, lm), INTENT(INOUT) :: qlls, qlcn, qils, &
&   qicn, clcn, clls
!Outs
    INTEGER, INTENT(OUT) :: irccode
    REAL*8, DIMENSION(im, jm, lm) :: dqs, qss
    REAL*8, DIMENSION(im, jm, lm) :: qst3
    REAL*8, DIMENSION(im, jm, lm) :: dzet, qddf3
    REAL*8, DIMENSION(im, jm) :: tpert, qpert
    REAL*8, DIMENSION(im, jm) :: mxdiamx
    REAL*8, DIMENSION(im, jm, lm) :: cnv_dqldt, cnv_mfd, cnv_prc3, &
&   cnv_updf, cnv_cvw, entlam
    INTEGER :: i, j, l, k
    CALL PRE_RASE(im, jm, lm, th1, q1, ts, cnv_fraction, frland, plo, &
&           pke, pk, cbl_tpert, cbl_qpert, cbl_tpert_mxocn, &
&           cbl_tpert_mxlnd, tpert, qpert, dqs, qss)
    CALL RASE(idim, irun, lm, icmin, dt_moist, doconvec, mapl8_cp, &
&       mapl8_alhl, mapl8_alhs, mapl8_tice, mapl8_grav, seedras, sige, &
&       kcbl, wgt0, wgt1, tpert, qpert, th1, q1, u1, v1, qss, dqs, &
&       cnv_fraction, rasal2_2d, co_auto, cnv_ple, pke, cnv_dqldt, &
&       cnv_mfd, cnv_prc3, cnv_updf, rasparams, itrcr)
    CALL PRE_PROGNO_CLOUD(im, jm, lm, th1, pk, plo, pke, cnv_ple, qst3, &
&                   dzet, qddf3, cnv_fraction, cldparams)
    CALL PROGNO_CLOUD(idim, lm, dt_moist, plo, cnv_ple, pk, frland, kh, &
&               cnv_mfd, cnv_dqldt, cnv_prc3, cnv_updf, u1, v1, th1, q1&
&               , qlls, qlcn, qils, qicn, clcn, clls, cldparams, &
&               sclmfdfr, qst3, dzet, qddf3, cnv_fraction)
  END SUBROUTINE MOIST_RUN
!  Differentiation of pre_rase in forward (tangent) mode (with options r8):
!   variations   of useful results: dqs tpert qss
!   with respect to varying inputs: th1 q1
  SUBROUTINE PRE_RASE_TLM(im, jm, lm, th1, th1_tl, q1, q1_tl, ts, &
&   cnv_fraction, frland, plo, pke, pk, cbl_tpert, cbl_qpert, &
&   cbl_tpert_mxocn, cbl_tpert_mxlnd, tpert, tpert_tl, qpert, dqs, &
&   dqs_tl, qss, qss_tl)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: im, jm, lm
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: th1, q1
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: th1_tl, q1_tl
    REAL*8, DIMENSION(im, jm), INTENT(IN) :: ts, cnv_fraction, frland
    REAL*8, INTENT(IN) :: cbl_tpert, cbl_qpert, cbl_tpert_mxocn, &
&   cbl_tpert_mxlnd
    REAL*8, DIMENSION(im, jm, 0:lm), INTENT(IN) :: pke
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: plo, pk
    REAL*8, DIMENSION(im, jm, lm), INTENT(OUT) :: dqs, qss
    REAL*8, DIMENSION(im, jm, lm), INTENT(OUT) :: dqs_tl, qss_tl
    REAL*8, DIMENSION(im, jm), INTENT(OUT) :: tpert, qpert
    REAL*8, DIMENSION(im, jm), INTENT(OUT) :: tpert_tl
    INTEGER :: i, j, l
    REAL*8, DIMENSION(im, jm, 0:lm) :: zle
    REAL*8, DIMENSION(im, jm, 0:lm) :: zle_tl
    REAL*8, DIMENSION(im, jm, lm) :: temp1, zlo
    REAL*8, DIMENSION(im, jm, lm) :: temp1_tl, zlo_tl
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC MIN
    REAL*8 :: abs0
    temp1_tl = pk*th1_tl
    temp1 = th1*pk
    zle(:, :, lm) = 0.
    zlo_tl = 0.0_8
    zle_tl = 0.0_8
    DO l=lm,1,-1
      zle_tl(:, :, l-1) = th1_tl(:, :, l)*(1.+mapl8_vireps*q1(:, :, l)) &
&       + th1(:, :, l)*mapl8_vireps*q1_tl(:, :, l)
      zle(:, :, l-1) = th1(:, :, l)*(1.+mapl8_vireps*q1(:, :, l))
      zlo_tl(:, :, l) = zle_tl(:, :, l) + mapl8_cp*(pke(:, :, l)-pk(:, :&
&       , l))*zle_tl(:, :, l-1)/mapl8_grav
      zlo(:, :, l) = zle(:, :, l) + mapl8_cp/mapl8_grav*(pke(:, :, l)-pk&
&       (:, :, l))*zle(:, :, l-1)
      zle_tl(:, :, l-1) = zlo_tl(:, :, l) + mapl8_cp*(pk(:, :, l)-pke(:&
&       , :, l-1))*zle_tl(:, :, l-1)/mapl8_grav
      zle(:, :, l-1) = zlo(:, :, l) + mapl8_cp/mapl8_grav*(pk(:, :, l)-&
&       pke(:, :, l-1))*zle(:, :, l-1)
    END DO
    dqs_tl = 0.0_8
    qss_tl = 0.0_8
    DO j=1,jm
      DO i=1,im
        CALL DQSATPERT_TLM(dqs(i, j, :), dqs_tl(i, j, :), qss(i, j, :), &
&                    qss_tl(i, j, :), temp1(i, j, :), temp1_tl(i, j, :)&
&                    , plo(i, j, :), lm)
      END DO
    END DO
    IF (cbl_tpert .GE. 0.) THEN
      abs0 = cbl_tpert
    ELSE
      abs0 = -cbl_tpert
    END IF
    tpert_tl = abs0*(-temp1_tl(:, :, lm)-mapl8_grav*zlo_tl(:, :, lm)/&
&     mapl8_cp)
    tpert = abs0*(ts-(temp1(:, :, lm)+mapl8_grav*zlo(:, :, lm)/mapl8_cp)&
&     )
    IF (cbl_tpert .LT. 0) THEN
! Make TPERT 0 in areas of deep convection
      tpert_tl = (1.0-cnv_fraction)*tpert_tl
      tpert = tpert*(1.0-cnv_fraction)
    END IF
!CBL_QPERT * ( QSSFC - Q(:,:,LM) )      !dh: CBL_QPERT = 0.0
    qpert = 0.0
    WHERE (tpert .LT. 0.0) 
      tpert_tl = 0.0_8
      tpert = 0.0
    ELSEWHERE
      tpert = tpert
    END WHERE
    WHERE (qpert .LT. 0.0) 
      qpert = 0.0
    ELSEWHERE
      qpert = qpert
    END WHERE
    WHERE (tpert .GT. cbl_tpert_mxocn) 
      tpert_tl = 0.0_8
      tpert = cbl_tpert_mxocn
    ELSEWHERE
      tpert = tpert
    END WHERE
    WHERE (tpert .GT. cbl_tpert_mxlnd) 
      tpert_tl = 0.0_8
      tpert = cbl_tpert_mxlnd
    ELSEWHERE
      tpert = tpert
    END WHERE
  END SUBROUTINE PRE_RASE_TLM
  SUBROUTINE PRE_RASE(im, jm, lm, th1, q1, ts, cnv_fraction, frland, plo&
&   , pke, pk, cbl_tpert, cbl_qpert, cbl_tpert_mxocn, cbl_tpert_mxlnd, &
&   tpert, qpert, dqs, qss)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: im, jm, lm
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: th1, q1
    REAL*8, DIMENSION(im, jm), INTENT(IN) :: ts, cnv_fraction, frland
    REAL*8, INTENT(IN) :: cbl_tpert, cbl_qpert, cbl_tpert_mxocn, &
&   cbl_tpert_mxlnd
    REAL*8, DIMENSION(im, jm, 0:lm), INTENT(IN) :: pke
    REAL*8, DIMENSION(im, jm, lm), INTENT(IN) :: plo, pk
    REAL*8, DIMENSION(im, jm, lm), INTENT(OUT) :: dqs, qss
    REAL*8, DIMENSION(im, jm), INTENT(OUT) :: tpert, qpert
    INTEGER :: i, j, l
    REAL*8, DIMENSION(im, jm, 0:lm) :: zle
    REAL*8, DIMENSION(im, jm, lm) :: temp1, zlo
    INTRINSIC ABS
    INTRINSIC MAX
    INTRINSIC MIN
    REAL*8 :: abs0
    temp1 = th1*pk
    zle(:, :, lm) = 0.
    DO l=lm,1,-1
      zle(:, :, l-1) = th1(:, :, l)*(1.+mapl8_vireps*q1(:, :, l))
      zlo(:, :, l) = zle(:, :, l) + mapl8_cp/mapl8_grav*(pke(:, :, l)-pk&
&       (:, :, l))*zle(:, :, l-1)
      zle(:, :, l-1) = zlo(:, :, l) + mapl8_cp/mapl8_grav*(pk(:, :, l)-&
&       pke(:, :, l-1))*zle(:, :, l-1)
    END DO
    DO j=1,jm
      DO i=1,im
        CALL DQSATPERT(dqs(i, j, :), qss(i, j, :), temp1(i, j, :), plo(i&
&                , j, :), lm)
      END DO
    END DO
    IF (cbl_tpert .GE. 0.) THEN
      abs0 = cbl_tpert
    ELSE
      abs0 = -cbl_tpert
    END IF
    tpert = abs0*(ts-(temp1(:, :, lm)+mapl8_grav*zlo(:, :, lm)/mapl8_cp)&
&     )
    IF (cbl_tpert .LT. 0) tpert = tpert*(1.0-cnv_fraction)
! Make TPERT 0 in areas of deep convection
!CBL_QPERT * ( QSSFC - Q(:,:,LM) )      !dh: CBL_QPERT = 0.0
    qpert = 0.0
    WHERE (tpert .LT. 0.0) 
      tpert = 0.0
    ELSEWHERE
      tpert = tpert
    END WHERE
    WHERE (qpert .LT. 0.0) 
      qpert = 0.0
    ELSEWHERE
      qpert = qpert
    END WHERE
    WHERE (tpert .GT. cbl_tpert_mxocn) 
      tpert = cbl_tpert_mxocn
    ELSEWHERE
      tpert = tpert
    END WHERE
    WHERE (tpert .GT. cbl_tpert_mxlnd) 
      tpert = cbl_tpert_mxlnd
    ELSEWHERE
      tpert = tpert
    END WHERE
  END SUBROUTINE PRE_RASE
END MODULE GEOS_MOISTGRIDCOMP_D
