1 (TC42) Recursivity: esinit-->qsatice0-->esinit
2 (TC42) Recursivity: qsatlqu0-->esinit-->qsatlqu0
3 qsat0: (TC19) Equality test on reals is not reliable
4 qsat0: (TC19) Equality test on reals is not reliable
5 qsat0: (TC19) Equality test on reals is not reliable
6 dqsat0: (TC19) Equality test on reals is not reliable
7 dqsat0: (TC19) Equality test on reals is not reliable
8 dqsat0: (TC19) Equality test on reals is not reliable
9 finddtls: (TC30) Type mismatch in argument 1 of procedure random_seed, expected INTEGER, is here INTEGER(*)
10 erfapp: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
11 erfapp: (TC16) Type mismatch in assignment: REAL*8 receives DOUBLE PRECISION
