1 a2b_ord4: (TC01) Expression is expected to be numeric, and is here INTEGER*()
2 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
3 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
4 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
5 a2b_ord4_fb: (TC01) Expression is expected to be numeric, and is here INTEGER*()
6 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
7 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
8 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
9 a2b_ord2: (TC01) Expression is expected to be numeric, and is here INTEGER*()
10 a2b_ord2: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
11 tracer_2d_nested: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
12 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
13 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
14 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
15 fv_tp_2d: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
16 fv_tp_2d_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
17 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
18 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
19 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
20 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
21 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
22 dyn_core: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
23 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
24 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
25 dyn_core: (TC01) Expression is expected to be numeric, and is here INTEGER*()
26 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
27 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
28 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
29 rayleigh_fast: (TC16) Type mismatch in assignment: REAL,kind=r_grid  receives DOUBLE PRECISION
30 lagrangian_to_eulerian: (TC16) Type mismatch in assignment: REAL*4 receives REAL,r8_kind 
31 lagrangian_to_eulerian: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
32 lagrangian_to_eulerian: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
33 lagrangian_to_eulerian: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
34 lagrangian_to_eulerian: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
35 lagrangian_to_eulerian: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
36 lagrangian_to_eulerian: (AD14) Summary: differentiated procedure of lagrangian_to_eulerian needs to save undeclared side-effect variables global_area, from COMMON /tapenade_save_g_sum/
37 steepz: (TC19) Equality test on reals is not reliable
38 ppm_limiters: (TC19) Equality test on reals is not reliable
39 fv_dynamics: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
40 fv_dynamics: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
41 fv_dynamics: (TC01) Expression is expected to be numeric, and is here INTEGER*()
42 fv_dynamics: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
43 fv_dynamics: (DF02) Potential aliasing in calling function setup_nested_grid_bcs, between arguments 18 21
44 fv_dynamics: (AD14) Checkpointing this call to setup_nested_grid_bcs needs to save an undeclared side-effect variable: (global)q_buf
45 fv_dynamics: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
46 fv_dynamics: (AD14) Checkpointing this call to g_sum needs to save an undeclared side-effect variable: (global_area SAVEd by g_sum)
47 fv_dynamics: (AD14) Summary: differentiated procedure of fv_dynamics needs to save undeclared side-effect variables global_area, from COMMON /tapenade_save_g_sum/
48 fv_dynamics: (AD14) Summary: differentiated procedure of fv_dynamics needs to save undeclared side-effect variables q_buf, from MODULE fv_nesting_mod
49 rayleigh_super: (TC16) Type mismatch in assignment: REAL receives REAL*8
50 rayleigh_friction: (TC16) Type mismatch in assignment: REAL receives REAL*8
51 setup_nested_grid_bcs: Tool: (Collect used pointer ranks) Unexpected operator: none
52 fv_grid_utils_mod_b: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
53 fv_grid_utils_mod_b: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
54 fv_grid_utils_mod_b: (TC16) Type mismatch in assignment: REAL receives DOUBLE PRECISION
55 dyn_core_mod_b: (TC16) Type mismatch in assignment: REAL,kind=r_grid  receives DOUBLE PRECISION
