!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:30
!
MODULE FV_DIAGNOSTICS_MOD_D
  USE FV_ARRAYS_MOD_D, ONLY : r_grid
  USE MPP_DOMAINS_MOD_D, ONLY : domain2d
  IMPLICIT NONE
  PRIVATE 
  PUBLIC fv_time, prt_mxm, range_check, prt_minmax, prt_maxmin, &
& sphum_ll_fix
  LOGICAL, PARAMETER :: prt_minmax=.false.
!dummy
  INTEGER :: fv_time
  REAL :: sphum_ll_fix

CONTAINS
  SUBROUTINE RANGE_CHECK(qname, q, is, ie, js, je, n_g, km, pos, q_low, &
&   q_hi, bad_range)
    IMPLICIT NONE
!Stubbed
    CHARACTER(len=*), INTENT(IN) :: qname
    INTEGER, INTENT(IN) :: is, ie, js, je
    INTEGER, INTENT(IN) :: n_g, km
    REAL, INTENT(IN) :: q(is-n_g:ie+n_g, js-n_g:je+n_g, km)
    REAL, INTENT(IN) :: pos(is-n_g:ie+n_g, js-n_g:je+n_g, 2)
    REAL, INTENT(IN) :: q_low, q_hi
    LOGICAL, OPTIONAL, INTENT(OUT) :: bad_range
  END SUBROUTINE RANGE_CHECK
  SUBROUTINE PRT_MXM(qname, q, is, ie, js, je, n_g, km, fac, area, &
&   domain)
    IMPLICIT NONE
!Stubbed
    CHARACTER(len=*), INTENT(IN) :: qname
    INTEGER, INTENT(IN) :: is, ie, js, je
    INTEGER, INTENT(IN) :: n_g, km
    REAL, INTENT(IN) :: q(is-n_g:ie+n_g, js-n_g:je+n_g, km)
    REAL, INTENT(IN) :: fac
    REAL(kind=r_grid), INTENT(IN) :: area(is-3:ie+3, js-3:je+3)
    TYPE(DOMAIN2D), INTENT(INOUT) :: domain
  END SUBROUTINE PRT_MXM
  SUBROUTINE PRT_MAXMIN(qname, q, is, ie, js, je, n_g, km, fac)
    IMPLICIT NONE
!Stubbed
    CHARACTER(len=*), INTENT(IN) :: qname
    INTEGER, INTENT(IN) :: is, ie, js, je
    INTEGER, INTENT(IN) :: n_g, km
    REAL, INTENT(IN) :: q(is-n_g:ie+n_g, js-n_g:je+n_g, km)
    REAL, INTENT(IN) :: fac
  END SUBROUTINE PRT_MAXMIN
END MODULE FV_DIAGNOSTICS_MOD_D
