!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:30
!
MODULE GROUP_CALL_MOD_D
  USE GROUP_SUBS_MOD_D
  IMPLICIT NONE
  PRIVATE 
  PUBLIC group_call_test
  PUBLIC group_call_test_tlm

CONTAINS
!  Differentiation of group_call_test in forward (tangent) mode:
!   variations   of useful results: v2 v3 u2 u3
!   with respect to varying inputs: v2 v3 u2 u3
!   RW status of diff variables: v2:in-out v3:in-out u2:in-out
!                u3:in-out
  SUBROUTINE GROUP_CALL_TEST_TLM(u2, u2_tl, v2, v2_tl, u3, u3_tl, v3, &
&   v3_tl, isd, ied, jsd, jed, npz)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: isd, ied, jsd, jed, npz
    REAL, INTENT(INOUT) :: u2(isd:ied, jsd:jed), v2(isd:ied, jsd:jed)
    REAL, INTENT(INOUT) :: u2_tl(isd:ied, jsd:jed), v2_tl(isd:ied, jsd:&
&   jed)
    REAL, INTENT(INOUT) :: u3(isd:ied, jsd:jed, npz), v3(isd:ied, jsd:&
&   jed, npz)
    REAL, INTENT(INOUT) :: u3_tl(isd:ied, jsd:jed, npz), v3_tl(isd:ied, &
&   jsd:jed, npz)
    CALL GROUP_UPDATE_TLM(u2, u2_tl, isd, ied, jsd, jed)
    CALL GROUP_UPDATE_TLM(u2, u2_tl, v2, v2_tl, isd, ied, jsd, jed)
    CALL GROUP_UPDATE_TLM(u3, u3_tl, isd, ied, jsd, jed, npz)
    CALL GROUP_UPDATE_TLM(u3, u3_tl, v3, v3_tl, isd, ied, jsd, jed, npz)
  END SUBROUTINE GROUP_CALL_TEST_TLM
  SUBROUTINE GROUP_CALL_TEST(u2, v2, u3, v3, isd, ied, jsd, jed, npz)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: isd, ied, jsd, jed, npz
    REAL, INTENT(INOUT) :: u2(isd:ied, jsd:jed), v2(isd:ied, jsd:jed)
    REAL, INTENT(INOUT) :: u3(isd:ied, jsd:jed, npz), v3(isd:ied, jsd:&
&   jed, npz)
    CALL GROUP_UPDATE(u2, isd, ied, jsd, jed)
    CALL GROUP_UPDATE(u2, v2, isd, ied, jsd, jed)
    CALL GROUP_UPDATE(u3, isd, ied, jsd, jed, npz)
    CALL GROUP_UPDATE(u3, v3, isd, ied, jsd, jed, npz)
  END SUBROUTINE GROUP_CALL_TEST
END MODULE GROUP_CALL_MOD_D
