!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.12 (r6213) - 13 Oct 2016 10:30
!
MODULE GROUP_SUBS_MOD_D
  IMPLICIT NONE
  PRIVATE 
  PUBLIC group_update
  PUBLIC group_update_tlm
  INTERFACE GROUP_UPDATE
      MODULE PROCEDURE GROUP_UPDATE_R2_V1
      MODULE PROCEDURE GROUP_UPDATE_R2_V2
      MODULE PROCEDURE GROUP_UPDATE_R3_V1
      MODULE PROCEDURE GROUP_UPDATE_R3_V2
  END INTERFACE GROUP_UPDATE

  INTERFACE GROUP_UPDATE_TLM
      MODULE PROCEDURE GROUP_UPDATE_R2_V1_TLM
      MODULE PROCEDURE GROUP_UPDATE_R2_V2_TLM
      MODULE PROCEDURE GROUP_UPDATE_R3_V1_TLM
      MODULE PROCEDURE GROUP_UPDATE_R3_V2_TLM
  END INTERFACE


CONTAINS
!  Differentiation of group_update_r2_v1 in forward (tangent) mode:
!   variations   of useful results: field1
!   with respect to varying inputs: field1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R2_V1_TLM(field1, field1_tl, is, ie, js, je)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je
    REAL, INTENT(INOUT) :: field1(is:ie, js:je)
    REAL, INTENT(INOUT) :: field1_tl(is:ie, js:je)
    field1_tl = 2*field1_tl
    field1 = 2*field1
  END SUBROUTINE GROUP_UPDATE_R2_V1_TLM
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R2_V1(field1, is, ie, js, je)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je
    REAL, INTENT(INOUT) :: field1(is:ie, js:je)
    field1 = 2*field1
  END SUBROUTINE GROUP_UPDATE_R2_V1
!  Differentiation of group_update_r2_v2 in forward (tangent) mode:
!   variations   of useful results: field1 field2
!   with respect to varying inputs: field1 field2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R2_V2_TLM(field1, field1_tl, field2, field2_tl&
&   , is, ie, js, je)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je
    REAL, INTENT(INOUT) :: field1(is:ie, js:je), field2(is:ie, js:je)
    REAL, INTENT(INOUT) :: field1_tl(is:ie, js:je), field2_tl(is:ie, js:&
&   je)
    field1_tl = 2*field1_tl
    field1 = 2*field1
    field2_tl = 2*field2_tl
    field2 = 2*field2
  END SUBROUTINE GROUP_UPDATE_R2_V2_TLM
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R2_V2(field1, field2, is, ie, js, je)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je
    REAL, INTENT(INOUT) :: field1(is:ie, js:je), field2(is:ie, js:je)
    field1 = 2*field1
    field2 = 2*field2
  END SUBROUTINE GROUP_UPDATE_R2_V2
!  Differentiation of group_update_r3_v1 in forward (tangent) mode:
!   variations   of useful results: field1
!   with respect to varying inputs: field1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R3_V1_TLM(field1, field1_tl, is, ie, js, je, k&
& )
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je, k
    REAL, INTENT(INOUT) :: field1(is:ie, js:je, k)
    REAL, INTENT(INOUT) :: field1_tl(is:ie, js:je, k)
    field1_tl = 2*field1_tl
    field1 = 2*field1
  END SUBROUTINE GROUP_UPDATE_R3_V1_TLM
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R3_V1(field1, is, ie, js, je, k)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je, k
    REAL, INTENT(INOUT) :: field1(is:ie, js:je, k)
    field1 = 2*field1
  END SUBROUTINE GROUP_UPDATE_R3_V1
!  Differentiation of group_update_r3_v2 in forward (tangent) mode:
!   variations   of useful results: field1 field2
!   with respect to varying inputs: field1 field2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R3_V2_TLM(field1, field1_tl, field2, field2_tl&
&   , is, ie, js, je, k)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je, k
    REAL, INTENT(INOUT) :: field1(is:ie, js:je, k), field2(is:ie, js:je&
&   , k)
    REAL, INTENT(INOUT) :: field1_tl(is:ie, js:je, k), field2_tl(is:ie, &
&   js:je, k)
    field1_tl = 2*field1_tl
    field1 = 2*field1
    field2_tl = 2*field2_tl
    field2 = 2*field2
  END SUBROUTINE GROUP_UPDATE_R3_V2_TLM
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  SUBROUTINE GROUP_UPDATE_R3_V2(field1, field2, is, ie, js, je, k)
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: is, ie, js, je, k
    REAL, INTENT(INOUT) :: field1(is:ie, js:je, k), field2(is:ie, js:je&
&   , k)
    field1 = 2*field1
    field2 = 2*field2
  END SUBROUTINE GROUP_UPDATE_R3_V2
END MODULE GROUP_SUBS_MOD_D
