1 a2b_ord4: (TC01) Expression is expected to be numeric, and is here INTEGER*()
2 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
3 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
4 a2b_ord4: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
5 a2b_ord4_fb: (TC01) Expression is expected to be numeric, and is here INTEGER*()
6 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
7 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
8 a2b_ord4_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
9 a2b_ord2: (TC01) Expression is expected to be numeric, and is here INTEGER*()
10 a2b_ord2: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
11 fv_tp_2d: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
12 fv_tp_2d_fb: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
13 drymadj: (TC16) Type mismatch in assignment: REAL,fvprc  receives REAL*4
14 dyn_core: (TC16) Type mismatch in assignment: REAL,fvprc [*] receives INTEGER
15 dyn_core: (TC16) Type mismatch in assignment: REAL,fvprc [*] receives INTEGER
16 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
17 dyn_core: (TC01) Expression is expected to be numeric, and is here INTEGER*()
18 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
19 dyn_core: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
20 tracer_2d_1l: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
21 tracer_2d_nested: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
22 tracer_2d_nested: (TC02) Expression is expected to be boolean, and is here BOOLEAN*()
23 fv_dynamics: (TC01) Expression is expected to be numeric, and is here INTEGER*()
24 fv_dynamics: (TC15) Argument of logical operator is expected to be boolean, and is here BOOLEAN*()
25 fv_dynamics: (TC16) Type mismatch in assignment: REAL,fvprc  receives REAL*4
26 lagrangian_to_eulerian: (TC16) Type mismatch in assignment: REAL,fvprc  receives REAL*4
27 dyn_core_mod_b: (TC16) Type mismatch in assignment: REAL,kind=r_grid  receives DOUBLE PRECISION
